### PR TITLE
Add vtkCurveGenerator

### PR DESCRIPTION
**Pull request by allemangD**
Code from Slicer at 84029a507dbf9f7f249e072ac99f649c7d55f239

Added classes:

- vtkCurveGenerator
- vtkLinearSpline
- vtkParametricPolynomialApproximation
- vtkSlicerDijkstraGraphGeodesicPath

---

See https://github.com/Slicer/Slicer/tree/84029a507dbf9f7f249e072ac99f649c7d55f239/Modules/Loadable/Markups/MRML

### CODE REVIEW

**Comment by jcfr** [comment]
Ideally we should rename `vtkSlicerDijkstraGraphGeodesicPath` to `vtkDijkstraGraphGeodesicPath` and, for backward compatibility, and update the class in Slicer to derive from it.

@lassoan  How does that sound ?

**Comment by Sunderlandkyl** [comment]
I don't recall. Probably we wanted to be able to experiment with the options without needing to go through a VTK PR + backporting every time.

**Comment by lassoan** [comment]
Ok. Then I think we should submit these additional features to the existing VTK class. We would probably also need to add some tests for the new modes.

@jcfr do you need to have this resolved in Slicer-5.2?

**Comment by jcfr** [comment]
In the meantime, I will move forward with the integration. Once VTK upstream is updated, we will deprecated `vtkSlicerDijkstraGraphGeodesicPath`

> we should submit these additional features to the existing VTK class. We would probably also need to add some tests for the new modes.

Agreed.

> do you need to have this resolved in Slicer-5.2?

We only need to have this PR merged, the update of Slicer can happen at a later time.

**Comment by jcfr** [comment]
### Original integration has been force-pushed

:warning: The commit originally associated with the `main` branch has been force-pushed as https://github.com/Slicer/vtkAddon/commit/2ae7f353192f9934d5c030bf35395f7fa81d5137 to include the relevant acknowledgment.  :warning:

**Pull request merged**
